name: Kustomize Build Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on PRs targeting the main branch

jobs:
  kustomize-build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout your repository code

    - name: Set up Kustomize
      run: |
        curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest \
        | jq -r '.assets[] | select(.name | test("linux.*tar.gz")) | .browser_download_url' \
        | xargs curl -LO
        tar -xzvf kustomize_v*.tar.gz
        mv kustomize /usr/local/bin/

    - name: Build with Kustomize
      run: |
        cd dev
        kustomize build . > configmap.yaml  # Run kustomize build and output to configmap.yaml

    - name: Commit and push configmap.yaml
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add configmap.yaml
        git commit -m "Update configmap.yaml"
        git push